### ISSUE TITLE
Add the ability to view closed polls

### ISSUE THREAD

**Issue by Natfan** [ganderzz/mob#5]
Possibly just a tab on the admin panel, but maybe adding the end point /polls/closed might be useful too?

**Comment by ganderzz** [comment]
Sounds like a great idea @Natfan . This one would be a bit more involved, but I'm open for a PR

**Comment by Natfan** [comment]
I'll see what I can do @ganderzz!

**Comment by Natfan** [comment]
Raised #6

**Comment by Natfan** [comment]
Found a bug. Index page doesn't show sharing option, fixed in #7

**Comment by ganderzz** [comment]
Thanks for the PR @Natfan ! Looks great
